services:
  app:
    image: jenrique138/app:3c4efcc465484b75045d55237016d8c012701591
    container_name: jenrique_dock
    ports:
      - "8080:3000"
    environment:
      DB_HOST: mysql-infra
      DB_USER: root
      DB_PASS: password
      DB_NAME: jenrique_dock
      DB_PORT: 3306
    networks:
      - rede_alunos

networks:
  rede_alunos:
    external: true

