services:
  app:
    image: jenrique138/app:ab0544c5aa8e69f708179815d8f9fd78044654bb
    container_name: jenrique_dock
    ports:
      - "8080:3000"
    environment:
      DB_HOST: mysql-infra
      DB_USER: root
      DB_PASS: password
      DB_NAME: jenrique_dock

networks:
  rede_alunos:
    external: true

